# Generated by Django 5.2.4 on 2025-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accounts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='slug'),
        ),
    ]
